In [3]:
import gnnco
import torch

# Testing Dense Graphs

In [2]:
adj_matrices = [torch.randn((5,5)) > 0 for _ in range(10)] + [torch.randn((10,10)) > 0 for _ in range(10)]
dgraphs = [gnnco.DenseGraph(adjacency_matrix=adj) for adj in adj_matrices]
batched_dgraphs = gnnco.BatchedDenseGraphs.from_graphs(dgraphs)
batched_sgraphs = batched_dgraphs.to_sparse()

In [3]:
dg1 = batched_dgraphs[0]
sg1 = batched_sgraphs[0]
assert (dg1.adj() == adj_matrices[0]).all(), "Test 1 failed"
assert (dg1.to_sparse().to_dense().adj() == dg1.adj()).all(), "Test 2 failed"
assert (sg1.to_dense().adj() == dg1.adj()).all(), "Test 3 failed"

In [4]:
print(dg1.to_sparse()._senders)
print(dg1.to_sparse()._receivers)

print(sg1._senders)
print(sg1._receivers)

tensor([0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4])
tensor([0, 0, 2, 0, 1, 2, 3, 0, 3, 4, 3])
tensor([0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4])
tensor([0, 0, 2, 0, 1, 2, 3, 0, 3, 4, 3])


In [5]:
sg1 = gnnco.SparseGraph(senders=torch.tensor([0,0,1,2]), receivers=torch.tensor([1,2,0,0]), order=3)
print(sg1.to_dense().adj())
sg2 = gnnco.SparseGraph(senders=torch.tensor([0,0,1,2]), receivers=torch.tensor([2,2,2,0]), order=3)
print(sg2.to_dense().adj())

tensor([[False,  True,  True],
        [ True, False, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False, False,  True],
        [ True, False, False]])


In [6]:
batch = gnnco.BatchedSparseGraphs.from_graphs([sg1, sg2])

In [7]:
print(batch._senders)
print(batch._receivers)
print(batch._batch)
print(batch._orders)

tensor([0, 0, 1, 2, 3, 3, 4, 5])
tensor([1, 2, 0, 0, 5, 5, 5, 3])
tensor([0, 0, 0, 0, 1, 1, 1, 1])
tensor([3, 3])


In [8]:
print(batch[0]._senders)
print(batch[0]._receivers)

print(batch[1]._senders)
print(batch[1]._receivers)

tensor([0, 0, 1, 2])
tensor([1, 2, 0, 0])
tensor([0, 0, 1, 2])
tensor([2, 2, 2, 0])


In [1]:
from gnnco import __all__

In [3]:
from torch import __all__

In [4]:
print(__all__)

['typename', 'is_tensor', 'is_storage', 'set_default_tensor_type', 'set_default_device', 'set_rng_state', 'get_rng_state', 'manual_seed', 'initial_seed', 'seed', 'save', 'load', 'set_printoptions', 'chunk', 'split', 'stack', 'matmul', 'no_grad', 'enable_grad', 'rand', 'randn', 'inference_mode', 'DoubleStorage', 'FloatStorage', 'LongStorage', 'IntStorage', 'ShortStorage', 'CharStorage', 'ByteStorage', 'BoolStorage', 'TypedStorage', 'UntypedStorage', 'DoubleTensor', 'FloatTensor', 'LongTensor', 'IntTensor', 'ShortTensor', 'CharTensor', 'ByteTensor', 'BoolTensor', 'Tensor', 'lobpcg', 'use_deterministic_algorithms', 'are_deterministic_algorithms_enabled', 'is_deterministic_algorithms_warn_only_enabled', 'set_deterministic_debug_mode', 'get_deterministic_debug_mode', 'set_float32_matmul_precision', 'get_float32_matmul_precision', 'set_warn_always', 'is_warn_always_enabled', 'SymInt', 'SymFloat', 'SymBool', 'sym_not', 'unravel_index', 'sym_int', 'sym_float', 'sym_max', 'sym_min', 'sym_ite', 